
/* __ ___ ____ _____ ______ _______ ________ _______ ______ _____ ____ ___ __
//
// Copyright (C) 1993-2005, ART+COM AG Berlin
//
// These coded instructions, statements, and computer programs contain
// unpublished proprietary information of ART+COM AG Berlin, and
// are copy protected by law. They may not be disclosed to third parties
// or copied or duplicated in any form, in whole or in part, without the
// specific, prior written permission of ART+COM AG Berlin.
// __ ___ ____ _____ ______ _______ ________ _______ ______ _____ ____ ___ __
//
//    $RCSfile: ShaderLibrary_xsd.cpp,v $
//
//   $Revision: 1.1 $
//
//      Author: 
//
// Description: 
//
//
// __ ___ ____ _____ ______ _______ ________ _______ ______ _____ ____ ___ __
*/

#include "ShaderLibrary_xsd.h"

const char * ourShaderLibrary_xsd = ""
"<?xml version='1.0' encoding='utf-8' ?>\n"
"<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>\n"
"   <xs:simpleType name='Point3f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='Vector3f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='Vector4f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='Vector2f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='Vector2i'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='VectorOfVector2i'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='VectorOfVector2f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='VectorOfVector3f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='VectorOfVector4f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='VectorOfString'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:simpleType name='Matrix4f'>\n"
"       <xs:restriction base='xs:string' />\n"
"   </xs:simpleType>\n"
"   <xs:element name='properties'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='unbounded'>\n"
"               <xs:element ref='float' />\n"
"               <xs:element ref='point3f' />\n"
"               <xs:element ref='vector2f' />\n"
"               <xs:element ref='vector3f' />\n"
"               <xs:element ref='vector4f' />\n"
"               <xs:element ref='matrix4f' />\n"
"               <xs:element ref='vectorofvector2f' />\n"
"               <xs:element ref='vectorofvector4f' />\n"
"               <xs:element ref='vectorofstring' />\n"
"               <xs:element ref='sampler1d' />\n"
"               <xs:element ref='sampler2d' />\n"
"               <xs:element ref='sampler3d' />\n"
"               <xs:element ref='samplerCUBE' />\n"
"           </xs:sequence>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='textures'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='unbounded'>\n"
"               <xs:element ref='texture' />\n"
"           </xs:sequence>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='texture'>\n"
"       <xs:complexType>\n"
"           <xs:attribute name='src' type='xs:string' />\n"
"           <xs:attribute name='name' type='xs:string' />\n"
"           <xs:attribute name='applymode' type='xs:string' />\n"
"           <xs:attribute name='wrapmode' type='xs:string' />\n"
"           <xs:attribute name='alpha' type='xs:int' />\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='float'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='xs:float'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"                   <xs:attribute name='function' type='xs:string' />\n"
"                   <xs:attribute name='register' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='sampler1d'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='xs:int'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='sampler2d'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='xs:int'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='sampler3d'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='xs:int'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vectorofvector2f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='VectorOfVector2f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vectorofvector4f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='VectorOfVector4f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vectorofstring'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='VectorOfString'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='samplerCUBE'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='xs:int'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vector4f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='Vector4f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"                   <xs:attribute name='function' type='xs:string' />\n"
"                   <xs:attribute name='register' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='matrix4f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='Matrix4f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"                   <xs:attribute name='function' type='xs:string' />\n"
"                   <xs:attribute name='register' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='point3f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='Point3f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vector2f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='Vector2f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"                   <xs:attribute name='function' type='xs:string' />\n"
"                   <xs:attribute name='register' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vector3f'>\n"
"       <xs:complexType>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='Vector3f'>\n"
"                   <xs:attribute name='name' type='xs:string' />\n"
"                   <xs:attribute name='function' type='xs:string' />\n"
"                   <xs:attribute name='register' type='xs:string' />\n"
"               </xs:extension>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='shaders'>\n"
"       <xs:complexType>\n"
"           <xs:sequence>\n"
"               <xs:element ref='shader' />\n"
"           </xs:sequence>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='shader'>\n"
"       <xs:complexType>\n"
"           <xs:sequence>\n"
"               <xs:element ref='supports' />\n"
"               <xs:element ref='fragmentshader' />\n"
"               <xs:element ref='vertexshader' />\n"
"               <xs:element ref='fixedfunctionshader' />\n"
"               <xs:element ref='textures' />\n"
"           </xs:sequence>\n"
"           <xs:attribute name='name' type='xs:string' />\n"
"           <xs:attribute name='id' type='xs:ID' />\n"
"           <xs:attribute name='cost' type='xs:float' />\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='supports'>\n"
"       <xs:complexType>\n"
"           <xs:sequence>\n"
"               <xs:element ref='feature' />\n"
"           </xs:sequence>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='feature'>\n"
"       <xs:complexType>\n"
"           <xs:attribute name='class' type='xs:IDREF' />\n"
"           <xs:attribute name='values' type='VectorOfString' />\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:complexType name='CgShader'>\n"
"       <xs:attribute name='file' type='xs:string' />\n"
"       <xs:attribute name='profile' type='xs:string' />\n"
"       <xs:attribute name='entryfunction' type='xs:string' />\n"
"       <xs:attribute name='compilerargs' type='xs:string' use='optional'/>\n"
"   </xs:complexType>\n"
"   <xs:element name='fragmentshader'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='1'>\n"
"               <xs:element ref='properties' />\n"
"           </xs:sequence>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='CgShader'/>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vertexshader'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='1'>\n"
"               <xs:element ref='properties' />\n"
"               <xs:element ref='vertexparameters' />\n"
"           </xs:sequence>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='CgShader'/>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='fixedfunctionshader'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='1'>\n"
"               <xs:element ref='properties' />\n"
"               <xs:element ref='vertexparameters' />\n"
"           </xs:sequence>\n"
"           <xs:simpleContent>\n"
"               <xs:extension base='CgShader'/>\n"
"           </xs:simpleContent>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"   <xs:element name='vertexparameters'>\n"
"       <xs:complexType>\n"
"           <xs:sequence minOccurs='0' maxOccurs='unbounded'>\n"
"               <xs:element ref='vector2f' />\n"
"               <xs:element ref='vector3f' />\n"
"               <xs:element ref='vector4f' />\n"
"               <xs:element ref='float' />\n"
"               <xs:element ref='sampler2d' />\n"
"           </xs:sequence>\n"
"       </xs:complexType>\n"
"   </xs:element>\n"
"</xs:schema>\n";
