// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.3.4

#ifndef __DirectorLink_skel_h__
#define __DirectorLink_skel_h__

#include <DirectorLink.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 3030400L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:DirectorLink:1.0
//
class DirectorLink_skel : virtual public DirectorLink,
                          virtual public CORBA_Object_skel
{
    DirectorLink_skel(const DirectorLink_skel&);
    void operator=(const DirectorLink_skel&);

protected:

    //
    // IDL:DirectorLink/callY50:1.0
    //
    OBDispatchStatus _OB_op_callY50(OBBuffer&, bool, CORBA_ULong, CORBA_ULong);

public:

    DirectorLink_skel() { }

    DirectorLink_ptr _this() { return DirectorLink::_duplicate(this); }

    virtual OBDispatchStatus _OB_dispatch(const char*, OBBuffer&, bool, CORBA_ULong, CORBA_ULong);

    //
    // IDL:DirectorLink/callY50:1.0
    //
    virtual char* callY50(const char* msg) = 0;
};

#endif
