#ifndef Y60_GLURFILTER_SETTING_INCLUDED
#define Y60_GLURFILTER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60GlurFilter_EXPORTS
#   define Y60_GLURFILTER_DECL AC_DLL_EXPORT
#else
#   define Y60_GLURFILTER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_GLURFILTER_SETTING_INCLUDED
