/* common/config.h.  Generated by configure.  */
/* common/config.h.in.  Generated from configure.ac by autoheader.  */


#ifndef WIN32
    /* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
       */
    #define HAVE_DIRENT_H 1

    /* Define to 1 if you have the <dlfcn.h> header file. */
    #define HAVE_DLFCN_H 1

    /* Define to 1 if you have the `getpagesize' function. */
    #define HAVE_GETPAGESIZE 1

    /* Define to 1 if you have the <inttypes.h> header file. */
    #define HAVE_INTTYPES_H 1

    /* Define to 1 if you have the `c' library (-lc). */
    #define HAVE_LIBC 1

    /* Define to 1 if you have the `m' library (-lm). */
    #define HAVE_LIBM 1

    /* Define to 1 if you have the `stdc' library (-lstdc). */
    /* #undef HAVE_LIBSTDC */

    /* Define to 1 if you have the `stdcx' library (-lstdcx). */
    /* #undef HAVE_LIBSTDCX */

    /* Define to 1 if you have the <memory.h> header file. */
    #define HAVE_MEMORY_H 1

    /* Define to 1 if you have a working `mmap' system call. */
    #define HAVE_MMAP 1

    /* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
    /* #undef HAVE_NDIR_H */

    /* Define to 1 if you have the <stdint.h> header file. */
    #define HAVE_STDINT_H 1

    /* Define to 1 if you have the <stdlib.h> header file. */
    #define HAVE_STDLIB_H 1

    /* Define to 1 if you have the <strings.h> header file. */
    #define HAVE_STRINGS_H 1

    /* Define to 1 if you have the <string.h> header file. */
    #define HAVE_STRING_H 1

    /* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
       */
    /* #undef HAVE_SYS_DIR_H */

    /* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
       */
    /* #undef HAVE_SYS_NDIR_H */

    /* Define to 1 if you have the <sys/stat.h> header file. */
    #define HAVE_SYS_STAT_H 1

    /* Define to 1 if you have the <sys/types.h> header file. */
    #define HAVE_SYS_TYPES_H 1

    /* Define to 1 if you have the <unistd.h> header file. */
    #define HAVE_UNISTD_H 1
#endif // #ifndef WIN32

/* Name of package */
#define PACKAGE "paintlib"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.6.1"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

// Byte order in a 32 bit word
#ifdef WORDS_BIGENDIAN
#define MSB_FIRST  // Motorola et al.
#else
#define LSB_FIRST // Intel et al.
#endif

#define PL_SUPPORT_TGA 1
#define PL_SUPPORT_BMP 1
#define PL_SUPPORT_TIFF 1
#define PL_SUPPORT_PICT 1
#ifdef _WIN32
  #define PL_SUPPORT_WEMF
  #define PL_PIXEL_BGRA_ORDER
#endif
#define PL_SUPPORT_PCX 1
#define PL_SUPPORT_PGM 1
#define PL_SUPPORT_PPM 1
#define PL_SUPPORT_PSD 1
#define PL_SUPPORT_SGI 1
#define PL_SUPPORT_IFF85 1

#define PL_SUPPORT_JPEG 1
#define PL_SUPPORT_PNG 1
#define PL_SUPPORT_GIF 1
#define PL_SUPPORT_CURL 1
/* #undef PL_SUPPORT_SDL */
/* #undef PL_SUPPORT_DFB */

