global proc acExportAll() {
    // Load plugin
    loadPlugin -quiet "mayaY60-export";

    // Export all
    $myFilename = `workspace -fullName` + "/test";
    print "Export file: ";
    print $myFilename;
    print "\n";
    if (catch(`file -op "binary=1;inlineTextures=0;" -typ "Y60" -pr -ea $myFilename`)) {
        print "Could not export file.\n";
    }

    // Unload plugin
    unloadPlugin "mayaY60-export";
}