#!/bin/bash

set -e

if [ "$DEBUG" == "1" ]; then
    VARIANT="DBG"
else
    VARIANT="OPT"
fi

if [ -z $MAYA_SDK ]; then
    echo "### ERROR: MAYA_SDK is not set"
    exit 1
fi

SCRIPT_DIR=""
if [ "$OS" == "Windows_NT" ] ; then
    cp -vf $PRO/lib/libeay32.dll "$MAYA_SDK/bin/"
    cp -vf $PRO/lib/libcurl.dll "$MAYA_SDK/bin/"
    cp -vf $PRO/lib/pthreadVC.dll "$MAYA_SDK/bin/"
    cp -vf $PRO/lib/ssleay32.dll "$MAYA_SDK/bin/"

    mkdir -p $MAYA_SDK/plug-ins
    mkdir -p $MAYA_SDK/scripts/others
    cp -vf o.ANT.WIN.${VARIANT}/mayaY60-export${VARIANT}.dll "$MAYA_SDK/bin/plug-ins/mayaY60export.mll"
    SCRIPT_DIR="$MAYA_SDK/scripts/others"
else
    if [ -z $MAYA_VERSION ]; then
        echo "### WARNING: MAYA_VERSION is not set"
    fi

    DIR="$HOME/maya/${MAYA_VERSION}"
    mkdir -p "${DIR}/plug-ins"

    cp -vf o.ANT.LINUX.${VARIANT}/libmayaY60-export${VARIANT}.so ${DIR}/plug-ins/mayaY60-export.so
    SCRIPT_DIR="${DIR}/scripts"
fi

echo "### INFO: Installing scripts to $SCRIPT_DIR"
mkdir -p "$SCRIPT_DIR"
cp -vf acY60XmlExportOptions.mel ${SCRIPT_DIR}
cp -vf acCreateObjectAttributes.mel ${SCRIPT_DIR}
cp -vf acCreateMaterialAttributes.mel ${SCRIPT_DIR}
cp -vf acCreateTextureAttributes.mel ${SCRIPT_DIR}
cp -vf acCreateLineAttributes.mel ${SCRIPT_DIR}
