#!/bin/bash

############################# common setup ############################################

PLUGIN_NAME=mayaY60-export
CODENAME=$PLUGIN_NAME

############################# linux setup #############################################

Y60_LINUX_LIBS="aslbase domxml y60base y60scene"

############################# windows setup ###########################################

Y60_WIN_LIBS="pthreadVC.dll libcurl.dll libeay32.dll ssleay32.dll"

WINDOWS_SYSTEM_LIBS="msvcp71.dll msvcp71d.dll msvcr71.dll msvcr71d.dll"
WINDOWS_SYSTEM32_DIR="$SYSTEMROOT/system32"

#######################################################################################

source $PRO/build/common_makedist

collectLinuxLibs() {
    echo "  Installing linux libraries"
    for LIB in $Y60_LINUX_LIBS; do
        LIBNAME=lib${LIB}OPT.so
        copyFile ${PRO}/lib/${LIBNAME} ${DIST_LIB_DIR};
        strip $DIST_LIB_DIR/${LIBNAME}
    done
}

makedistLinux() {
    echo "Building linux distribution";
    PACKAGENAME=${PLUGIN_NAME}-linux.tar.bz2
    DIST_BIN_DIR=${DIST_DIR}/${CODENAME}/maya/${MAYA_VERSION}
    DIST_LIB_DIR=${DIST_DIR}/${CODENAME}/lib

    removeDistribution

    echo "    Creating distribution directories"
    mkdir -p ${DIST_LIB_DIR}
    mkdir -p ${DIST_BIN_DIR}/plug-ins
    mkdir -p ${DIST_BIN_DIR}/scripts

    collectLinuxLibs

    echo "    Installing plugin"
    copyFile o.ANT.LINUX.OPT/lib${PLUGIN_NAME}OPT.so ${DIST_BIN_DIR}/plug-ins/${CODENAME}.so
    copyWildSet . "*.mel" ${DIST_BIN_DIR}/scripts

    echo "    Creating tar archive"
    cd ${DIST_BIN_DIR}
    tar cjf ../../${PACKAGENAME} *

    removeIntermediates
}

makedistWindows() {
    echo "Building windows distribution"
    PACKAGENAME=${PLUGIN_NAME}_setup
    DIST_BIN_DIR=${DIST_DIR}/${CODENAME}_setup

    removeDistribution

    echo "    Creating distribution directories"
    mkdir -p ${DIST_BIN_DIR}/plug-ins
    mkdir -p ${DIST_BIN_DIR}/scripts

    echo "    Copy Y60 libraries"
    copySet $PRO/lib "$Y60_WIN_LIBS" ${DIST_BIN_DIR}

    echo "    Installing plugin"
    REVISION=`cd $PRO && svn info | sed -n 's/^Revision: \(\d*\)/\1/p'`
    copyFile o.ANT.WIN.OPT/${PLUGIN_NAME}OPT.dll ${DIST_BIN_DIR}/plug-ins/mayaY60export${REVISION}.mll
    copyFile setup.bat ${DIST_BIN_DIR}
    copyWildSet . "*.mel" ${DIST_BIN_DIR}/scripts

    echo "    Copy windows system libraries"
    copySet $WINDOWS_SYSTEM32_DIR "$WINDOWS_SYSTEM_LIBS" $DIST_BIN_DIR
}

SUCCESS=0

startMessage

if [ -d o.ANT.WIN.OPT ]; then
    makedistWindows
    SUCCESS=1
fi

if [ -d o.ANT.LINUX.OPT ]; then
    makedistLinux
    SUCCESS=1
fi

endMessage $SUCCESS $PACKAGENAME
