#ifndef Y60_DINPUTFFB_SETTING_INCLUDED
#define Y60_DINPUTFFB_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef DInputFFB_EXPORTS
#   define Y60_DINPUTFFB_EXPORT AC_DLL_EXPORT
#else
#   define Y60_DINPUTFFB_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_DINPUTFFB_SETTING_INCLUDED
