#ifndef Y60_DSHOWCAPTURE_SETTING_INCLUDED
#define Y60_DSHOWCAPTURE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60DShowCapture_EXPORTS
#   define Y60_DSHOWCAPTURE_EXPORT AC_DLL_EXPORT
#else
#   define Y60_DSHOWCAPTURE_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_DSHOWCAPTURE_SETTING_INCLUDED
