#ifndef Y60_WMADECODER_SETTING_INCLUDED
#define Y60_WMADECODER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef wmadecoder_EXPORTS
#   define Y60_WMADECODER_DECL AC_DLL_EXPORT
#else
#   define Y60_WMADECODER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_WMADECODER_SETTING_INCLUDED
