#ifndef Y60_TESTRENDEREREXTENSION_SETTING_INCLUDED
#define Y60_TESTRENDEREREXTENSION_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef testRendererExtension_EXPORTS
#   define Y60_TESTRENDEREREXTENSION_DECL AC_DLL_EXPORT
#else
#   define Y60_TESTRENDEREREXTENSION_DECL AC_DLL_IMPORT
#endif

#endif // Y60_TESTRENDEREREXTENSION_SETTING_INCLUDED
