#ifndef Y60_WIIMOTE_SETTING_INCLUDED
#define Y60_WIIMOTE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60wiimote_EXPORTS
#   define Y60_WIIMOTE_EXPORT AC_DLL_EXPORT
#else
#   define Y60_WIIMOTE_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_WIIMOTE_SETTING_INCLUDED
