#ifndef Y60_OSCSENDER_SETTING_INCLUDED
#define Y60_OSCSENDER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60OscSender_EXPORTS
#   define Y60_OSCSENDER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_OSCSENDER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_OSCSENDER_SETTING_INCLUDED
