#ifndef Y60_MODELLING_SETTING_INCLUDED
#define Y60_MODELLING_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60modelling_EXPORTS
#   define Y60_MODELLING_DECL AC_DLL_EXPORT
#else
#   define Y60_MODELLING_DECL AC_DLL_IMPORT
#endif

#endif // Y60_MODELLING_SETTING_INCLUDED
