#ifndef Y60_VIDEOPROCESSING_SETTING_INCLUDED
#define Y60_VIDEOPROCESSING_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef videoprocessing_EXPORTS
#   define Y60_VIDEOPROCESSING_EXPORT AC_DLL_EXPORT
#else
#   define Y60_VIDEOPROCESSING_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_VIDEOPROCESSING_SETTING_INCLUDED
