#! /bin/bash

MODELNAME="$1"
if [ "$2" == "" ] ; then
    if [ "$USE_CG" == "1" ] ; then
        SHADERLIB=$PRO/src/Y60/shader/shaderlibrary.xml
    else
    	SHADERLIB=$PRO/src/Y60/shader/shaderlibrary_nocg.xml
    fi
else
    SHADERLIB="$2"
fi

shift
shift

APPLICATION=acxpshellOPT

if [ "$DEBUG" == "VG" ]; then
    if [ -x `which valgrind` ]; then
        APPLICATION="valgrind --tool=memcheck --leak-check=yes --show-reachable=yes acxpshellDBG"
    else
        APPLICATION="acxpshellDBG"
    fi
elif [ "$DEBUG" == "1" ] ; then
    APPLICATION="acxpshellDBG"
fi

#
# spidermonkey and kernel 2.6 pthreads need this to
# avoid a floating point exception on loading
#
if uname -r | grep -q "^2.6" ; then
    export LD_ASSUME_KERNEL="2.4.99"
    echo "setting LD_ASSUME_KERNEL=2.4.99"
fi

SCRIPT=$PRO/src/Y60/js/sv.js

BASENAME="${MODELNAME%.*}"
if [ -e ${BASENAME}.js ]; then
    SCRIPT=${BASENAME}.js
fi

ARGS="-I $PRO/src/Y60/js;$PRO/lib $SCRIPT $MODELNAME $SHADERLIB $*"

if [ "$DEBUG" = "vc" ]; then
    echo Visual Studio Debuger Setup
    echo --------------------------------------------------------------------------------------
    echo $PRO/bin/acxpshellDBG.exe
    echo $ARGS
    echo `cmd /C cd`
    echo --------------------------------------------------------------------------------------
    exit 0
fi

COMMAND="$APPLICATION $ARGS"
echo $COMMAND
$COMMAND
exit $?
