#! /bin/bash
MODELNAME="$1"
if [ "$2" == "" ] ; then
    SHADERLIB=$PRO/src/Y60/shader/shaderlibrary_nocg.xml 
else
    SHADERLIB="$2"
fi

shift
shift

acxpshellOPT -I $PRO/src/Y60/js/ testTextureAnimation.js $PRO/testmodels/texanimtest/plane.x60 $PRO/src/Y60/shader/shaderlibrary_nocg.xml $*
