#ifndef Y60_OSCRECEIVER_SETTING_INCLUDED
#define Y60_OSCRECEIVER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef OscReceiver_EXPORTS
#   define Y60_OSCRECEIVER_DECL AC_DLL_EXPORT
#else
#   define Y60_OSCRECEIVER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_OSCRECEIVER_SETTING_INCLUDED
