#ifndef Y60_SYNERGYSERVER_SETTING_INCLUDED
#define Y60_SYNERGYSERVER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef synergyserver_EXPORTS
#   define Y60_SYNERGYSERVER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_SYNERGYSERVER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_SYNERGYSERVER_SETTING_INCLUDED
