#ifndef Y60_SDLENGINE_SETTING_INCLUDED
#define Y60_SDLENGINE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60sdlengine_EXPORTS
#   define Y60_SDLENGINE_DECL AC_DLL_EXPORT
#else
#   define Y60_SDLENGINE_DECL AC_DLL_IMPORT
#endif

#endif // Y60_SDLENGINE_SETTING_INCLUDED
