#ifndef Y60_EDGEBLENDER_SETTING_INCLUDED
#define Y60_EDGEBLENDER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef EdgeBlender_EXPORTS
#   define Y60_EDGEBLENDER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_EDGEBLENDER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_EDGEBLENDER_SETTING_INCLUDED
