#ifndef Y60_JSSOUND_SETTING_INCLUDED
#define Y60_JSSOUND_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef Sound_EXPORTS
#   define Y60_JSSOUND_DECL AC_DLL_EXPORT
#else
#   define Y60_JSSOUND_DECL AC_DLL_IMPORT
#endif

#endif // Y60_JSSOUND_SETTING_INCLUDED
