#ifndef Y60_WMTOUCH_SETTING_INCLUDED
#define Y60_WMTOUCH_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60WMTouch_EXPORTS
#   define Y60_WMTOUCH_DECL AC_DLL_EXPORT
#else
#   define Y60_WMTOUCH_DECL AC_DLL_IMPORT
#endif

#endif // Y60_WMTOUCH_SETTING_INCLUDED
