#ifndef Y60_DEMOMODELLINGRENDEX_SETTING_INCLUDED
#define Y60_DEMOMODELLINGRENDEX_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef DemoModellingRendex_EXPORTS
#   define Y60_DEMOMODELLINGRENDEX_DECL AC_DLL_EXPORT
#else
#   define Y60_DEMOMODELLINGRENDEX_DECL AC_DLL_IMPORT
#endif

#endif // Y60_DEMOMODELLINGRENDEX_SETTING_INCLUDED
