#! /bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: `basename $0` <modelname> [<shaderlibrary>] [<arguments> ...]"
    exit 1
fi
MODELNAME="$1"
shift

APPLICATION="y60"

SCRIPT="sv.js"
BASENAME="${MODELNAME%.*}"
if [ -e ${BASENAME}.js ]; then
    SCRIPT=${BASENAME}.js
fi

ARGS=" $SCRIPT $MODELNAME $*"
COMMAND="$APPLICATION $ARGS"

echo $COMMAND
$COMMAND
exit $?
