#ifndef Y60_CLUSTEREXTENSION_SETTING_INCLUDED
#define Y60_CLUSTEREXTENSION_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef Cluster_EXPORTS
#   define Y60_CLUSTEREXTENSION_DECL AC_DLL_EXPORT
#else
#   define Y60_CLUSTEREXTENSION_DECL AC_DLL_IMPORT
#endif

#endif // Y60_CLUSTEREXTENSION_SETTING_INCLUDED
