// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.2
// License: 2-5-990601-1

#ifndef __DirectorLink_skel_h__
#define __DirectorLink_skel_h__

#include "DirectorLink.h"

//
// IDL:DirectorLink:1.0
//
class DirectorLink_skel : virtual public DirectorLink,
                          virtual public CORBA_Object_skel
{
    DirectorLink_skel(const DirectorLink_skel&);
    void operator=(const DirectorLink_skel&);

protected:

    //
    // IDL:DirectorLink/callY50:1.0
    //
    OBDispatchStatus _OB_op_callY50(OBBuffer&, bool, CORBA_ULong, CORBA_ULong);

public:

    DirectorLink_skel() { }

    DirectorLink_ptr _this() { return DirectorLink::_duplicate(this); }

    virtual OBDispatchStatus _OB_dispatch(const char*, OBBuffer&, bool, CORBA_ULong, CORBA_ULong);

    //
    // IDL:DirectorLink/callY50:1.0
    //
    virtual char* callY50(const char* msg) = 0;
};

#endif
