#ifndef Y60_POWERMATE_SETTING_INCLUDED
#define Y60_POWERMATE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef Powermate_EXPORTS
#   define Y60_POWERMATE_EXPORT AC_DLL_EXPORT
#else
#   define Y60_POWERMATE_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_POWERMATE_SETTING_INCLUDED
