#!/bin/bash
if [ "$C4D" == "" ] ; then
    echo "### Error: Environment variable \$C4D must be set to your Cinema4d directory"
    exit 1
fi

source $PRO/build/common_makedist

DIST_BIN_DIR="${C4D}"
if [ "$DEBUG" == "1" ] ; then
    SOURCEFILE="o.ANT.WIN.DBG/cinemaxY60-exportDBG.dll"
else
    SOURCEFILE="o.ANT.WIN.OPT/cinemaxY60-exportOPT.dll"
fi
if [ ! -f "$SOURCEFILE" ]; then
    echo "### Error: No such file '$SOURCEFILE'"
    exit 1
fi

echo "* Creating package directories"
mkdir -p "$DIST_BIN_DIR/Plugins/Y60/res/description"
mkdir -p "$DIST_BIN_DIR/Plugins/Y60/res/strings_us"
mkdir -p "$DIST_BIN_DIR/Plugins/Y60/res/strings_us/description"

echo "* Copying files"
copyFile $SOURCEFILE "$DIST_BIN_DIR/Plugins/Y60/cinemaxY60-export.cdl"
copyFile res/c4d_symbols.h       "$DIST_BIN_DIR/Plugins/Y60/res/c4d_symbols.h"
copyFile res/Facbinaryexport.h   "$DIST_BIN_DIR/Plugins/Y60/res/description"
copyFile res/Facbinaryexport.res "$DIST_BIN_DIR/Plugins/Y60/res/description"
copyFile res/Facxmlexport.h      "$DIST_BIN_DIR/Plugins/Y60/res/description"
copyFile res/Facxmlexport.res    "$DIST_BIN_DIR/Plugins/Y60/res/description"
copyFile res/c4d_strings.str     "$DIST_BIN_DIR/Plugins/Y60/res/strings_us/c4d_strings.str"
copyFile res/Facbinaryexport.str "$DIST_BIN_DIR/Plugins/Y60/res/strings_us/description"
copyFile res/Facxmlexport.str    "$DIST_BIN_DIR/Plugins/Y60/res/strings_us/description"

echo "* Done"
