#! /bin/sh

prefix=/usr/local/martin/PRO60
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: paintlib-config [OPTION]

Known values for OPTION are:

  --prefix      show Paintlib installation prefix 
  --libs        print library linking information
  --cflags      print pre-processor and compiler flags
  --help        display this help and exit
  --version     output version information


EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
    prefix=$optarg
    ;;

    --prefix)
    echo $prefix
    ;;

    --version)
    echo 2.6.1
    exit 0
    ;;

    --help)
    usage 0
    ;;

    --cflags)
        echo -g -O2 -I${prefix}/include -D_REENTRANT 
        ;;

    --libs)
        if test "$OSTYPE" == "darwin7.0"; then
            echo -lpaintlib
        else
            echo -lz -lpng -ljpeg -ltiff -lungif -lcurl -L${exec_prefix}/lib -lpaintlib
        fi
        ;;
    *)
    usage
    exit 1
    ;;
    esac
    shift
done

exit 0
