#ifndef Y60_GSTREAMERCAPTURE_SETTING_INCLUDED
#define Y60_GSTREAMERCAPTURE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef GStreamerCapture_EXPORTS
#   define Y60_GSTREAMERCAPTURE_EXPORT AC_DLL_EXPORT
#else
#   define Y60_GSTREAMERCAPTURE_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_GSTREAMERCAPTURE_SETTING_INCLUDED
