#ifndef Y60_X3DIMPORTER_SETTING_INCLUDED
#define Y60_X3DIMPORTER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60X3dImporter_EXPORTS
#   define Y60_X3DIMPORTER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_X3DIMPORTER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_X3DIMPORTER_SETTING_INCLUDED
