#ifndef Y60_CMSCACHE_SETTING_INCLUDED
#define Y60_CMSCACHE_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60CMSCache_EXPORTS
#   define Y60_CMSCACHE_DECL AC_DLL_EXPORT
#else
#   define Y60_CMSCACHE_DECL AC_DLL_IMPORT
#endif

#endif // Y60_CMSCACHE_SETTING_INCLUDED
