#ifndef Y60_STLIMPORTER_SETTING_INCLUDED
#define Y60_STLIMPORTER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60StlImporter_EXPORTS
#   define Y60_STLIMPORTER_DECL AC_DLL_EXPORT
#else
#   define Y60_STLIMPORTER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_STLIMPORTER_SETTING_INCLUDED
