#ifndef Y60_GLBINDING_SETTING_INCLUDED
#define Y60_GLBINDING_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef GLBinding_EXPORTS
#   define Y60_GLBINDING_DECL AC_DLL_EXPORT
#else
#   define Y60_GLBINDING_DECL AC_DLL_IMPORT
#endif

#endif // Y60_GLBINDING_SETTING_INCLUDED
