#ifndef Y60_OPENEXRDECODER_SETTING_INCLUDED
#define Y60_OPENEXRDECODER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60OpenEXRDecoder_EXPORTS
#   define Y60_OPENEXRDECODER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_OPENEXRDECODER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_OPENEXRDECODER_SETTING_INCLUDED
