#ifndef Y60_FFMPEGDECODER3_SETTING_INCLUDED
#define Y60_FFMPEGDECODER3_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef FFMpegDecoder3_EXPORTS
#   define Y60_FFMPEGDECODER3_DECL AC_DLL_EXPORT
#else
#   define Y60_FFMPEGDECODER3_DECL AC_DLL_IMPORT
#endif

#endif // Y60_FFMPEGDECODER3_SETTING_INCLUDED
