#ifndef Y60_QUICKTIMEDECODER_SETTING_INCLUDED
#define Y60_QUICKTIMEDECODER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60QuicktimeDecoder_EXPORTS
#   define Y60_QUICKTIMEDECODER_DECL AC_DLL_EXPORT
#else
#   define Y60_QUICKTIMEDECODER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_QUICKTIMEDECODER_SETTING_INCLUDED
