#ifndef Y60_OSCCLIENT_SETTING_INCLUDED
#define Y60_OSCCLIENT_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef OscClient_EXPORTS
#   define Y60_OSCCLIENT_EXPORT AC_DLL_EXPORT
#else
#   define Y60_OSCCLIENT_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_OSCCLIENT_SETTING_INCLUDED
