#ifndef Y60_SIMWATER_SETTING_INCLUDED
#define Y60_SIMWATER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef simwater_EXPORTS
#   define Y60_SIMWATER_EXPORT AC_DLL_EXPORT
#else
#   define Y60_SIMWATER_EXPORT AC_DLL_IMPORT
#endif

#endif // Y60_SIMWATER_SETTING_INCLUDED
