#ifndef Y60_ASSSCHEMA_SETTING_INCLUDED
#define Y60_ASSSCHEMA_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60ASSSchema_EXPORTS
#   define Y60_ASSSCHEMA_DECL AC_DLL_EXPORT
#else
#   define Y60_ASSSCHEMA_DECL AC_DLL_IMPORT
#endif

#endif // Y60_ASSSCHEMA_SETTING_INCLUDED
