#ifndef Y60_CSVIMPORTER_SETTING_INCLUDED
#define Y60_CSVIMPORTER_SETTING_INCLUDED

#include <asl/base/settings.h>

#ifdef y60CSVImporter_EXPORTS
#   define Y60_CSVIMPORTER_DECL AC_DLL_EXPORT
#else
#   define Y60_CSVIMPORTER_DECL AC_DLL_IMPORT
#endif

#endif // Y60_CSVIMPORTER_SETTING_INCLUDED
